//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicek_Siniflandirma.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cicek_Siniflandirma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1,3.5,1.4,0.2,Iris-setosa
        ///4.9,3.0,1.4,0.2,Iris-setosa
        ///4.7,3.2,1.3,0.2,Iris-setosa
        ///4.6,3.1,1.5,0.2,Iris-setosa
        ///5.0,3.6,1.4,0.2,Iris-setosa
        ///5.4,3.9,1.7,0.4,Iris-setosa
        ///4.6,3.4,1.4,0.3,Iris-setosa
        ///5.0,3.4,1.5,0.2,Iris-setosa
        ///4.4,2.9,1.4,0.2,Iris-setosa
        ///4.9,3.1,1.5,0.1,Iris-setosa
        ///5.4,3.7,1.5,0.2,Iris-setosa
        ///4.8,3.4,1.6,0.2,Iris-setosa
        ///4.8,3.0,1.4,0.1,Iris-setosa
        ///4.3,3.0,1.1,0.1,Iris-setosa
        ///5.8,4.0,1.2,0.2,Iris-setosa
        ///5.7,4.4,1.5,0.4,Iris-setosa
        ///5.4,3.9,1.3,0.4,Iris-setosa
        ///5.1,3.5,1.4,0.3,Iri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1,3.5,1.4,0.2,Iris-setosa
        ///4.9,3.0,1.4,0.2,Iris-setosa
        ///4.7,3.2,1.3,0.2,Iris-setosa
        ///4.6,3.1,1.5,0.2,Iris-setosa
        ///5.0,3.6,1.4,0.2,Iris-setosa
        ///5.4,3.9,1.7,0.4,Iris-setosa
        ///4.6,3.4,1.4,0.3,Iris-setosa
        ///5.0,3.4,1.5,0.2,Iris-setosa
        ///4.4,2.9,1.4,0.2,Iris-setosa
        ///4.9,3.1,1.5,0.1,Iris-setosa
        ///5.4,3.7,1.5,0.2,Iris-setosa
        ///4.8,3.4,1.6,0.2,Iris-setosa
        ///4.8,3.0,1.4,0.1,Iris-setosa
        ///4.3,3.0,1.1,0.1,Iris-setosa
        ///5.8,4.0,1.2,0.2,Iris-setosa
        ///5.7,4.4,1.5,0.4,Iris-setosa
        ///5.4,3.9,1.3,0.4,Iris-setosa
        ///5.1,3.5,1.4,0.3,Iri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string iris {
            get {
                return ResourceManager.GetString("iris", resourceCulture);
            }
        }
    }
}
